<a href="https://colab.research.google.com/github/Lakshmi-krishna-vr/ML-foundations-and-advanced-techniques/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy numerical python

In [ ]:
import numpy as np

## list vs numpy

In [ ]:
from time import process_time

## time table by a list

In [ ]:
python_list= [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time= process_time()
print(end_time - start_time)


0.0007124069999999705


In [ ]:
np_array = np.array([i for i in range(100000)])
start_time = process_time()
np_array +=5
end_time = process_time()
print(end_time - start_time)

0.000806666999999095


## numpy array

In [ ]:
#list
l1=[1,2,3,4,5]
print(l1)
type(l1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b=np.array([(1,2,3),(94,5,6)],dtype=float)
print(b)

[[ 1.  2.  3.]
 [94.  5.  6.]]


In [ ]:
b.shape

(2, 3)

## initial placeholders in numpy array

In [ ]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.full((5,3),6))

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.random.random((3,4)))

[[0.45968774 0.06298403 0.68201527 0.80999865]
 [0.54086381 0.83911787 0.47257263 0.30082494]
 [0.69493963 0.98788265 0.32806113 0.72633978]]


In [ ]:
print(np.random.randint(10,100,(5,6)))

[[84 93 93 54 52 95]
 [74 80 72 45 33 13]
 [50 79 59 83 99 36]
 [62 56 88 15 71 27]
 [99 73 50 46 20 23]]


In [ ]:
print(np.linspace(10,30,5))

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values
print(np.arange(10,30,5))

[10 15 20 25]


In [ ]:
#convert an list to an array
list2= [10,20,30,40]
print(np.asarray(list2))
type(np.asarray(list2))

[10 20 30 40]


numpy.ndarray

## analysing numpy array